[context.production]
  environment = { NODE_VERSION = "14.16.0" }
  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      cache-control = '''
    	max-age=0,
  	  no-cache,
  	  no-store,
  	  must-revalidate'''
