[context.production]
  environment = { NODE_VERSION = "14.16.0" }
  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Content-Security-Policy = "default-src 'self'";
      X-Content-Type-Options = "nosniff"
      Referrer-Polic =  "strict-origin-when-cross-origin"
      Permissions-Policy = "geolocation=(self), microphone=(), camera=(), fullscreen=*"
